### ISSUE TITLE
ValueError: The transport can not be bound to any-address

### ISSUE THREAD

**Issue by cdh4u** [aellwein/lwm2mclient#11]
I am trying to run your client.py code on macOS, by connecting to the Leshan demo server, and get the following error:

2020-06-09 16:27:01,726 [DEBUG] Using selector: KqueueSelector
2020-06-09 16:27:01,731 [ERROR] Task exception was never retrieved
future: <Task finished coro=<Client.run() done, defined at client.py:151> exception=ValueError('The transport can not be bound to any-address.')>
Traceback (most recent call last):
  File "client.py", line 153, in run
    self.context = await Context.create_server_context(self, bind=('::', 0))
  File "/usr/local/lib/python3.7/site-packages/aiocoap-0.4a1-py3.7.egg/aiocoap/protocol.py", line 576, in create_server_context
    self.transport_endpoints.append((yield from TransportEndpointSimpleServer.create_server(bind, new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop)))
  File "/usr/local/lib/python3.7/site-packages/aiocoap-0.4a1-py3.7.egg/aiocoap/transports/simplesocketserver.py", line 117, in create_server
    self._pool = yield from _DatagramServerSocketSimple.create(server_address, log, self._loop, self._received_datagram, self._received_exception)
  File "/usr/local/lib/python3.7/site-packages/aiocoap-0.4a1-py3.7.egg/aiocoap/transports/simplesocketserver.py", line 60, in create
    raise ValueError("The transport can not be bound to any-address.")
ValueError: The transport can not be bound to any-address.

I did find the aiocoap issue https://github.com/chrysn/aiocoap/issues/101.

But, when trying by setting an explicit IP address (IPv4, as I am not assigned an IPv6 address), I get the following error:

ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.

**Comment by cdh4u** [comment]
I also tried on Windows10, getting the same errors.

**Comment by aellwein** [comment]
@cdh4u can you please provide more details on how you specified the explicit IP address? 
It is indeed not allows to have the ``reuse_address`` option specified in any way (it's even not there since Python 3.8). 
Details can be found here: https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_data#asyncio.loop.create_datagram_endpoint

**Comment by aellwein** [comment]
@cdh4u it seems that [this commit](https://github.com/chrysn/aiocoap/commit/792fbf779e28a8bc7826b53c4bb838ccd210b7cf) may have fixed this issue. Can you test it on Windows against aiocoap 0.4b2?

**Comment by cdh4u** [comment]
> 0.4b2

Still getting an error:

2020-06-16 17:39:31,228 [DEBUG] Using proactor: IocpProactor
2020-06-16 17:39:31,244 [ERROR] Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Client.run() done, defined at client.py:151> exception=ValueError('The transport can not be bound to any-address.')>
Traceback (most recent call last):
  File "client.py", line 152, in run
    self.context = await Context.create_server_context(self, bind=('::', 0))
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\protocol.py", line 239, in create_server_context
    await self._append_tokenmanaged_messagemanaged_transport(
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\protocol.py", line 147, in _append_tokenmanaged_messagemanaged_transport
    transport = await message_interface_constructor(mman)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\transports\simplesocketserver.py", line 144, in create_server
    self._pool = await _DatagramServerSocketSimple.create(bind, log, self._loop, self._received_datagram, self._received_exception)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\transports\simplesocketserver.py", line 83, in create
    raise ValueError("The transport can not be bound to any-address.")
ValueError: The transport can not be bound to any-address.


I modified the setup.py file, in order to use aiocoap 0.4b2:

setup(
    name='lwm2mclient',
    version='0.1.0+git',
    description='Lightweight M2M Client written in Python',
    author='Alexander Ellwein',
    author_email='alex.ellwein@gmail.com',
    license='MIT License',
    install_requires=[
        'aiocoap==0.4b2',
        'hexdump==3.3'
    ]
)

**Comment by aellwein** [comment]
@cdh4u i see. From what i can tell you right now -- the aiocoap implementation tries to use "simplesocketserver" transport and it fails; at least on Windows. I can hardly suggest anything here since i have no Windows system to test on and i'm lacking understanding on how these transports are working internally. 
Maybe @chrysn can suggest something?

**Comment by cdh4u** [comment]
> @cdh4u i see. From what i can tell you right now -- the aiocoap implementation tries to use "simplesocketserver" transport and it fails; at least on Windows. I can hardly suggest anything here since i have no Windows system to test on and i'm lacking understanding on how these transports are working internally.
> Maybe @chrysn can suggest something?

Note that I get the same error when trying on a Mac.

**Comment by cdh4u** [comment]
> @cdh4u i see. From what i can tell you right now -- the aiocoap implementation tries to use "simplesocketserver" transport and it fails; at least on Windows. I can hardly suggest anything here since i have no Windows system to test on and i'm lacking understanding on how these transports are working internally.
> Maybe @chrysn can suggest something?
> 
> Note that I get the same error when trying on a Mac.

Just want to double check that the following command does not have to be modified due to changes in aiocoap:

self.context = await Context.create_server_context(self, bind=('::', 0))

**Comment by aellwein** [comment]
Ok, i've got a Mac here, now i can reproduce this using both aiocoap 0.4a1 and 0.4b2.
Interestingly, using 0.4a1 and following command

``env AIOCOAP_SERVER_TRANSPORT="simple6" ./client.py``


i've managed to connect to local Leshan server, 
so you can may be try that on Windows,
however, there is another exception using "simple6" transport and aiocoap 0.4b2:
```
future: <Task finished name='Task-1' coro=<Client.run() done, defined at ./client.py:151> exception=AttributeError("'NoneType' object has no attribute 'scheme'")>
Traceback (most recent call last):
  File "./client.py", line 162, in run
    response = await self.context.request(request).response
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 720, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 745, in _run
    await protocol.find_remote_and_interface(app_request)
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
    if await ri.fill_or_recognize_remote(message):
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/tokenmanager.py", line 179, in fill_or_recognize_remote
    return await self.token_interface.fill_or_recognize_remote(message)
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/messagemanager.py", line 330, in fill_or_recognize_remote
    remote = await self.message_interface.determine_remote(message)
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/transports/generic_udp.py", line 23, in determine_remote
    if request.requested_scheme not in ('coap', None):
  File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/message.py", line 543, in requested_scheme
    return self.remote.scheme
AttributeError: 'NoneType' object has no attribute 'scheme'
```

**Comment by cdh4u** [comment]
> Ok, i've got a Mac here, now i can reproduce this using both aiocoap 0.4a1 and 0.4b2.
> Interestingly, using 0.4a1 and following command
> env AIOCOAP_SERVER_TRANSPORT="simple6" ./client.py
> i've managed to connect to local Leshan server,
> so you can may be try that on Windows,
> however, there is another exception using "simple6" transport and aiocoap 0.4b2:
> future: <Task finished name='Task-1' coro=<Client.run() done, defined at ./client.py:151> exception=AttributeError("'NoneType' object has no attribute 'scheme'")>
> Traceback (most recent call last):
>   File "./client.py", line 162, in run
>     response = await self.context.request(request).response
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 720, in _run_outer
>     await cls._run(app_request, response, weak_observation, protocol, log)
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 745, in _run
>     await protocol.find_remote_and_interface(app_request)
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
>     if await ri.fill_or_recognize_remote(message):
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/tokenmanager.py", line 179, in fill_or_recognize_remote
>     return await self.token_interface.fill_or_recognize_remote(message)
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/messagemanager.py", line 330, in fill_or_recognize_remote
>     remote = await self.message_interface.determine_remote(message)
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/transports/generic_udp.py", line 23, in determine_remote
>     if request.requested_scheme not in ('coap', None):
>   File "/Users/alex/git/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4b2-py3.8.egg/aiocoap/message.py", line 543, in requested_scheme
>     return self.remote.scheme
> AttributeError: 'NoneType' object has no attribute 'scheme'

When I try with 0.4b2 I get the same error as you.

When I try with 0.4a1 I get the following error message:

"OSError: [WinError 10049] The requested address is not valid in its context"

**Comment by aellwein** [comment]
> When I try with 0.4a1 I get the following error message:
> 
> "OSError: [WinError 10049] The requested address is not valid in its context"

This can have different reasons. May be your system is lacking IPv6 support or 
something else.

In this line

``self.context = await Context.create_server_context(self, bind=('::', 0))``

a CoAP server is started to listen on '::' which means any address in IPv6 scheme. 

The LwM2M works in the fashion that a LwM2M client is actually becoming a server
(i.e. listening for requests) after the registration with LwM2M server. 
That's why the bind and listening is necessary.
You can try to use a different address in bind(), maybe '::1' (loopback), 
this would however only work for local server <-> client scenario,
not sure if a full qualified IPv4 address would work here, but you can try it.

**Comment by cdh4u** [comment]
> When I try with 0.4a1 I get the following error message:
> "OSError: [WinError 10049] The requested address is not valid in its context"
> 
> This can have different reasons. May be your system is lacking IPv6 support or
> something else.

I do have IPv6 on the Mac. 

> In this line
> self.context = await Context.create_server_context(self, bind=('::', 0))
> a CoAP server is started to listen on '::' which means any address in IPv6 scheme.
> The LwM2M works in the fashion that a LwM2M client is actually becoming a server
> (i.e. listening for requests) after the registration with LwM2M server.
> That's why the bind and listening is necessary.

Correct. 

Not sure if I mentioned it earlier, but if I try to run the code in client mode only, things work, because then you don't need to binding.

> You can try to use a different address in bind(), maybe '::1' (loopback),
> this would however only work for local server <-> client scenario,
> not sure if a full qualified IPv4 address would work here, but you can try it.

I have tried every option I could think of :) 

Next I am going to create a Linux VM and try.

**Comment by chrysn** [comment]
Thanks for pinging me, I can offer some insight here: A CoAP server always needs to know which IP address a request was sent to in order to send a response from the same address. (Otherwise, weird subtle bugs come up as soon as a system is configured with multiple IP addresses, eg. when the user activates privacy addresses or the network administrator starts renumbering).

There are two ways to obtain that information:
* Set an option in the socket to get the destination address ("RECVPKTINFO") -- this is unavailable on Windows and somewhat hidden on macOS
* Bind the socket to a particular IP address

aiocoap supports different transport implementations. On Linux, the udp6 version can be used, and binding to the any-address ('::') Just Works (because of other features that actually enable such operation). On Windows and macOS, that available, and the simplesocketserver is the next best thing. That doesn't need all the OS features, but in return needs the user to specify the IP address to bind to (which eliminates the need for fancy OS interactions).

Is it workable for lwm2mclient to have the user specify the local address?

If not, it might make sense in this particular application to only use the simple6 *client* transport -- as while what is being run is technically a CoAP server, it (as far as I understand LwM2M) only ever interacts with its LwM2M server, and that is contacted first. (The simple6 transport works by connecting a UDP socket, and thus automatically gets a stable local IP address.)

**Comment by aellwein** [comment]
Thanks for clarification!

> Is it workable for lwm2mclient to have the user specify the local address?

This is currently not configurable, the address was hard-coded to '::' for simplicity's sake and used to work for me (on Linux), but to be honest i didn't used the client for a while.

I can make the necessary changes to make this address configurable.

**Comment by aellwein** [comment]
@chrysn @cdh4u option for specifying an address has been added, but still another error appears, at least on Mac:
```
Traceback (most recent call last):
  File "./client.py", line 154, in run
    self.context = await Context.create_server_context(self, bind=(self.address, 0))
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/protocol.py", line 576, in create_server_context
    self.transport_endpoints.append((yield from TransportEndpointSimpleServer.create_server(bind, new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop)))
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 117, in create_server
    self._pool = yield from _DatagramServerSocketSimple.create(server_address, log, self._loop, self._received_datagram, self._received_exception)
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 64, in create
    transport, protocol = yield from loop.create_datagram_endpoint(
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1291, in create_datagram_endpoint
    raise ValueError("Passing `reuse_address=True` is no "
ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.
```
Note: the client is still using aiocoap 0.4a1.

**Comment by chrysn** [comment]
I'll need to make that configurable (or use reuseport) for the next release as Python 3.9 unfortunately drops support for this. In the mean time, things should work if you patch out the reuse_address=True around

```
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 64, in create
    transport, protocol = yield from loop.create_datagram_endpoint(
```

but clearly that's not very practical. I'll make https://github.com/chrysn/aiocoap/issues/181 and a release with it added a priority. It's odd that this shows up way ahead of schedule, but meh.

**Comment by cdh4u** [comment]
> @chrysn @cdh4u option for specifying an address has been added, but still another error appears, at least on Mac:
> Traceback (most recent call last):
>   File "./client.py", line 154, in run
>     self.context = await Context.create_server_context(self, bind=(self.address, 0))
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/protocol.py", line 576, in create_server_context
>     self.transport_endpoints.append((yield from TransportEndpointSimpleServer.create_server(bind, new_message_callback=self._dispatch_message, new_error_callback=self._dispatch_error, log=self.log, loop=loop)))
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 117, in create_server
>     self._pool = yield from _DatagramServerSocketSimple.create(server_address, log, self._loop, self._received_datagram, self._received_exception)
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 64, in create
>     transport, protocol = yield from loop.create_datagram_endpoint(
>   File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1291, in create_datagram_endpoint
>     raise ValueError("Passing `reuse_address=True` is no "
> ValueError: Passing `reuse_address=True` is no longer supported, as the usage of SO_REUSEPORT in UDP poses a significant security concern.
> 
> Note: the client is still using aiocoap 0.4a1.

FYI: Same error on Windows (using 0.4a1).

**Comment by cdh4u** [comment]
> I'll need to make that configurable (or use reuseport) for the next release as Python 3.9 unfortunately drops support for this. In the mean time, things should work if you patch out the reuse_address=True around
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap-0.4a1-py3.8.egg/aiocoap/transports/simplesocketserver.py", line 64, in create
>     transport, protocol = yield from loop.create_datagram_endpoint(
> 
> but clearly that's not very practical. I'll make chrysn/aiocoap#181 and a release with it added a priority. It's odd that this shows up way ahead of schedule, but meh.

I tried with aiocoap 0.4b2, which removes reuse_address=True, and adds reuse_port=True, and now I got the following error on Windows:

ValueError: reuse_port not supported by socket module

I then tried by removing reuse_port=True, but then I got the following error:

Traceback (most recent call last):
  File "client.py", line 164, in run
    response = await self.context.request(request).response
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\protocol.py", line 720, in _run_outer
    await cls._run(app_request, response, weak_observation, protocol, log)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\protocol.py", line 745, in _run
    await protocol.find_remote_and_interface(app_request)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\protocol.py", line 295, in find_remote_and_interface
    if await ri.fill_or_recognize_remote(message):
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\tokenmanager.py", line 179, in fill_or_recognize_remote
    return await self.token_interface.fill_or_recognize_remote(message)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\transports\tcp.py", line 478, in fill_or_recognize_remote
    if message.requested_scheme == self._scheme:
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b2-py3.8.egg\aiocoap\message.py", line 543, in requested_scheme
    return self.remote.scheme
AttributeError: 'NoneType' object has no attribute 'scheme'

**Comment by chrysn** [comment]
On Wed, Jun 17, 2020 at 12:35:42PM -0700, Christer Holmberg wrote:
> ValueError: reuse_port not supported by socket module
> 
> I then tried by removing reuse_port=True, but then I got the following error:

In that case, you can just leave out all reuse_* options -- things will
still work, and the next aiocoap release will be smarter about this.

**Comment by cdh4u** [comment]
> On Wed, Jun 17, 2020 at 12:35:42PM -0700, Christer Holmberg wrote:
>  ValueError: reuse_port not supported by socket module
> 
>  I then tried by removing reuse_port=True, but then I got the following error:
> In that case, you can just leave out all reuse_* options -- things will
> still work, and the next aiocoap release will be smarter about this.

I did. This is the modified code I used (simplesocketserver.py), which caused the error above:

        transport, protocol = await loop.create_datagram_endpoint(
                lambda: cls(ready.set_result, new_message_callback, new_error_callback, log),
                local_addr=bind)

However, the scheme problem is probably not related to the socket.

**Comment by cdh4u** [comment]
On Wed, Jun 17, 2020 at 12:35:42PM -0700, Christer Holmberg wrote:
ValueError: reuse_port not supported by socket module
I then tried by removing reuse_port=True, but then I got the following error:
In that case, you can just leave out all reuse_* options -- things will
still work, and the next aiocoap release will be smarter about this.

I did. This is the modified code I used (simplesocketserver.py), which caused the error above:
transport, protocol = await loop.create_datagram_endpoint(
lambda: cls(ready.set_result, new_message_callback, new_error_callback, log),
local_addr=bind)

However, the scheme problem is probably not related to the socket.

Seems like the fix is to add the uri to the Message command:

    request = Message(code=Code.POST, payload=','.join(
        self.model.get_object_links()).encode(), uri="coap://<server_address>:5683")
The original code is:

    request = Message(code=Code.POST, payload=','.join(self.model.get_object_links()).encode())
    request.opt.uri_host = self.server
    request.opt.uri_port = self.server_port
However, that does not seem to add the scheme.

**Comment by cdh4u** [comment]
Once I have managed to register witht the server (Leshan), and try to read a value, I get the following error:

    raise RuntimeError("Simple6 can not access local host info")

**Comment by aellwein** [comment]
> Seems like the fix is to add the uri to the Message command:
> 
> ```
> request = Message(code=Code.POST, payload=','.join(
>     self.model.get_object_links()).encode(), uri="coap://<server_address>:5683")
> ```
> 
> The original code is:
> 
> ```
> request = Message(code=Code.POST, payload=','.join(self.model.get_object_links()).encode())
> request.opt.uri_host = self.server
> request.opt.uri_port = self.server_port
> ```
> 
> However, that does not seem to add the scheme.

Good catch, thank you. It used to work without the scheme back then, but now the scheme seems to be required. I can fix that in lwm2mclient.
I wish i had integration tests here...

**Comment by chrysn** [comment]
The new 0.4b3 version should fix all problems related to the reuse_* options; if a bind address is set, things should work even on Windows (tested with a demo program) and macOS (not tested).

As for the "Simple6 can not access local host info", I'd need to know where this is flying out from. I think I can make it available, but I'd like to first understand why it is relevant in the first place. (Quite possibly, this was a follow-up error from a different error being raised that tried to get the connection's details -- but there as well, I'd need a stack trace to work with.)

**Comment by aellwein** [comment]
@chrysn i managed to reproduce the exception above. The stack trace is
```
2020-06-18 15:50:01,325 [ERROR] An exception occurred while rendering a resource: RuntimeError('Simple6 can not access local host info')
Traceback (most recent call last):
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/protocol.py", line 351, in _render_to_plumbing_request
    await self._render_to_plumbing_request_inner(plumbing_request,
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/protocol.py", line 375, in _render_to_plumbing_request_inner
    needs_blockwise = await self.serversite.needs_blockwise_assembly(request)
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/resource.py", line 315, in needs_blockwise_assembly
    child, subrequest = self._find_child_and_pathstripped_message(request)
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/resource.py", line 335, in _find_child_and_pathstripped_message
    request.get_request_uri(local_is_server=True))
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/message.py", line 443, in get_request_uri
    netloc = refmsg.remote.hostinfo_local
  File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/transports/simple6.py", line 85, in hostinfo_local
    raise RuntimeError("Simple6 can not access local host info")
```

**Comment by cdh4u** [comment]
> @chrysn i managed to reproduce the exception above. The stack trace is
> 2020-06-18 15:50:01,325 [ERROR] An exception occurred while rendering a resource: RuntimeError('Simple6 can not access local host info')
> Traceback (most recent call last):
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/protocol.py", line 351, in _render_to_plumbing_request
>     await self._render_to_plumbing_request_inner(plumbing_request,
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/protocol.py", line 375, in _render_to_plumbing_request_inner
>     needs_blockwise = await self.serversite.needs_blockwise_assembly(request)
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/resource.py", line 315, in needs_blockwise_assembly
>     child, subrequest = self._find_child_and_pathstripped_message(request)
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/resource.py", line 335, in _find_child_and_pathstripped_message
>     request.get_request_uri(local_is_server=True))
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/message.py", line 443, in get_request_uri
>     netloc = refmsg.remote.hostinfo_local
>   File "/Users/alex/git/private/lwm2mclient/.venv/lib/python3.8/site-packages/aiocoap/transports/simple6.py", line 85, in hostinfo_local
>     raise RuntimeError("Simple6 can not access local host info")

Similar error on Windows (using 0.4b3 version):

2020-06-18 21:11:10,186 [DEBUG] Incoming message <aiocoap.Message at 0x3d91118: Type.CON GET (MID 15982, token 9cb6eda51161990f) remote <_Connection at 0x3db0c28 on transport <_ProactorDatagramTransport fd=900 read=<_OverlappedFuture pending overlapped=<pending, 0x3d95d38> cb=[_ProactorDatagramTransport._loop_reading()]>>, active>, 2 option(s)>
2020-06-18 21:11:10,186 [DEBUG] New unique message received
2020-06-18 21:11:10,186 [ERROR] An exception occurred while rendering a resource: RuntimeError('Simple6 can not access local host info')
Traceback (most recent call last):
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\protocol.py", line 351, in _render_to_plumbing_request
    await self._render_to_plumbing_request_inner(plumbing_request,
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\protocol.py", line 375, in _render_to_plumbing_request_inner
    needs_blockwise = await self.serversite.needs_blockwise_assembly(request)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\resource.py", line 315, in needs_blockwise_assembly
    child, subrequest = self._find_child_and_pathstripped_message(request)
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\resource.py", line 335, in _find_child_and_pathstripped_message
    request.get_request_uri(local_is_server=True))
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\message.py", line 443, in get_request_uri
    netloc = refmsg.remote.hostinfo_local
  File "C:\Users\lmfchh\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiocoap-0.4b3-py3.8.egg\aiocoap\transports\simple6.py", line 85, in hostinfo_local
    raise RuntimeError("Simple6 can not access local host info")
RuntimeError: Simple6 can not access local host info

**Comment by cdh4u** [comment]
@chrysn, did the logs help?

**Comment by chrysn** [comment]
Yes, thank you. I was caught up in other issues the last few days, just coming back to it now.

In the end what this shows is that the current test cases (that do run the simple6 transport) never play through role reversal. Most servers that rely on role reversal probably don't do virtual hosting and have no actual *reason* to introspect the local URI; so far I'm evaluating the different approaches (ensuring that a local host info can be constructed on simple6 vs. ensuring that the local hostinfo is only accessed when needed), and how those could be tested.

**Comment by chrysn** [comment]
I've implemented access to hostinfo_local in current aiocoap master, could you give it a try? It works for me in my ad-hoc tests, but there's no systematic (CI) testing yet.

**Comment by cdh4u** [comment]
> I've implemented access to hostinfo_local in current aiocoap master, could you give it a try? It works for me in my ad-hoc tests, but there's no systematic (CI) testing yet.

It seems to work now. When I try to read (6/0/0) from Leshan, I can see the following log:

2020-06-24 15:00:55,246 [DEBUG] read on 6/0/0
Received read
2020-06-24 15:00:55,247 [DEBUG] encode_resource(): 00000000: 32 37 2E 39 38 36 30 36  35                       27.986065
2020-06-24 15:00:55,247 [DEBUG] Sending message <aiocoap.Message at 0x40963b8: Type.ACK 2.05 Content (MID 12371, token f4ca15c20d4affe1) remote <_Connection at 0x4090c28 on transport <_ProactorDatagramTransport fd=788 read=<_OverlappedFuture pending overlapped=<pending, 0x4075d38> cb=[_ProactorDatagramTransport._loop_reading()]>>, active>, 9 byte(s) payload>

However, in Leshan I now get the following error/alert:

Unable to read resource /6/0/0 for python-client : 500 Invalid Response:Unable to decode response payload of request [ReadRequest [path=/6/0/0 format=ContentFormat [name=TLV, code=11542]]] from client [python-client]

**Comment by chrysn** [comment]
> It seems to work now.

Thanks, that's good to know.

> Unable to decode response payload

That sounds like a very different issue (confirming that the transport trouble has been resolved); you might want to track that in a new issue.

**Comment by cdh4u** [comment]
> It seems to work now.
> 
> Thanks, that's good to know.
> 
> Unable to decode response payload
> 
> That sounds like a very different issue (confirming that the transport trouble has been resolved); you might want to track that in a new issue.

Yes, I will open a new issue. Just wanted to give a complete status update :)

**Comment by cdh4u** [comment]
> It seems to work now.
> Thanks, that's good to know.
> Unable to decode response payload
> That sounds like a very different issue (confirming that the transport trouble has been resolved); you might want to track that in a new issue.
> 
> Yes, I will open a new issue. Just wanted to give a complete status update :)

https://github.com/aellwein/lwm2mclient/issues/12

**Comment by aellwein** [comment]
@cdh4u i added "coap" scheme as you suggested in lwm2mclient, thanks for the hint.
I think this issue can be closed now.
